### ISSUE TITLE
PR to Logux Redux

### ISSUE THREAD

**Issue by ai** [vkalinichev/logux-vuex#1]
Hi. That idea of `createLoguxCreator(loguxOpts) → createStore(storeOpts) → store` is really clever.

Do you want to send PR to `logux-redux` with aweome ideas from `logux-vuex`?

1. The diff in docs example.
2. Two function call, to nothave `undefined, undefined` in the middle of `createLoguxStore()` args?

**Comment by vkalinichev** [comment]
Open PR: https://github.com/logux/logux-redux/pull/2

Thanks for opportunity!
